import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'social', title: 'Social Platforms', icon: 'Users', count: 12 },
  { id: 'video', title: 'Video Platforms', icon: 'Video', count: 8 },
  { id: 'saas', title: 'SaaS Tools', icon: 'Briefcase', count: 15 },
  { id: 'admin', title: 'Admin Dashboards', icon: 'Layout', count: 9 },
];

export const PRODUCTS: Product[] = [
  {
    id: 'wesocial',
    title: 'Wesocial',
    description: 'A premium social networking platform with real-time messaging and media sharing.',
    price: 59,
    rating: 4.8,
    sales: 1240,
    updatedAt: '2 days ago',
    tags: ['React', 'Node.js', 'Socket.io'],
    thumbnail: 'https://picsum.photos/seed/social1/800/600',
    category: 'Social Platforms',
    isFeatured: true,
    isTrending: true,
  },
  {
    id: 'shortz',
    title: 'Shortz',
    description: 'Short-form video sharing platform like TikTok, optimized for performance.',
    price: 49,
    rating: 4.7,
    sales: 850,
    updatedAt: '1 week ago',
    tags: ['Next.js', 'FFmpeg', 'AWS'],
    thumbnail: 'https://picsum.photos/seed/video1/800/600',
    category: 'Video Platforms',
    isFeatured: true,
  },
  {
    id: 'nexus',
    title: 'Nexus',
    description: 'The ultimate SaaS boilerplate with authentication, billing, and team management.',
    price: 99,
    rating: 5.0,
    sales: 420,
    updatedAt: 'Today',
    tags: ['Next.js', 'Stripe', 'Prisma'],
    thumbnail: 'https://picsum.photos/seed/saas1/800/600',
    category: 'SaaS Tools',
    isFeatured: true,
    isBestSeller: true,
  },
  {
    id: 'livewire',
    title: 'Livewire',
    description: 'Real-time collaboration tool for remote teams with shared whiteboards.',
    price: 69,
    rating: 4.9,
    sales: 720,
    updatedAt: '3 days ago',
    tags: ['WebSocket', 'Canvas', 'React'],
    thumbnail: 'https://picsum.photos/seed/tool1/800/600',
    category: 'SaaS Tools',
    isTrending: true,
  },
  {
    id: 'playstream',
    title: 'Playstream',
    description: 'Advanced live streaming engine with low-latency delivery and chat integrations.',
    price: 89,
    rating: 4.6,
    sales: 510,
    updatedAt: '5 days ago',
    tags: ['WebRTC', 'RTMP', 'Go'],
    thumbnail: 'https://picsum.photos/seed/stream1/800/600',
    category: 'Video Platforms',
    isFeatured: true,
  },
  {
    id: 'admin-pro',
    title: 'AdminPro',
    description: 'Feature-rich admin dashboard template with 50+ pre-built components.',
    price: 39,
    rating: 4.5,
    sales: 2100,
    updatedAt: '2 weeks ago',
    tags: ['Tailwind', 'Vue', 'Chart.js'],
    thumbnail: 'https://picsum.photos/seed/admin1/800/600',
    category: 'Admin Dashboards',
    isBestSeller: true,
  }
];
